CI: add the following CI test:
- `PCT enabled`
- `PCT enabled + broken`
- `Custom zeroization (explicit_bzero)`

Signed-off-by: willieyz <willie.zhao@chelpis.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -379,6 +379,38 @@ jobs:
     runs-on: ${{ matrix.target.runner }}
     steps:
       - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+      - name: "PCT enabled"
+        uses: ./.github/actions/multi-functest
+        with:
+          gh_token: ${{ secrets.GITHUB_TOKEN }}
+          compile_mode: native
+          cflags: "-DMLD_CONFIG_KEYGEN_PCT -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
+          func: true
+          kat: true
+          acvp: true
+      - name: "PCT enabled + broken"
+        run: |
+          make clean
+          CFLAGS='-DMLD_CONFIG_FILE=\"../test/break_pct_config.h\"' make func -j4
+          # PCT breakage is done at runtime via MLD_BREAK_PCT
+          make run_func                 # Should be OK
+          MLD_BREAK_PCT=0 make run_func # Should be OK
+          if (MLD_BREAK_PCT=1 make run_func 2>&1 >/dev/null); then
+             echo "PCT failure expected"
+             exit 1
+          else
+             echo "PCT failed as expected"
+          fi
+      - name: "Custom zeroization (explicit_bzero)"
+        uses: ./.github/actions/multi-functest
+        with:
+          gh_token: ${{ secrets.GITHUB_TOKEN }}
+          compile_mode: native
+          cflags: "-std=c11 -D_GNU_SOURCE -DMLD_CONFIG_FILE=\\\\\\\"../test/custom_zeroize_config.h\\\\\\\" -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
+          func: true
+          kat: true
+          acvp: true
+          examples: false # Some examples use a custom config themselves
       - name: "No ASM"
         uses: ./.github/actions/multi-functest
         with:
